In [32]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
pd.set_option('display.float_format', lambda x: '%.3f' % x)

In [4]:
df = pd.read_csv('/Users/devonbancroft/Desktop/Devon-GA-DAT-10-14/Data/housing.csv')

In [5]:
def mse(idx, target):
    error = target[idx].mean()-target[idx]
    return np.mean(error**2)

In [6]:
df.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD  TAX  PTRATIO  \
0  0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296     15.3   
1  0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242     17.8   
2  0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242     17.8   
3  0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222     18.7   
4  0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222     18.7   

        B  LSTAT  PRICE  
0  396.90   4.98   24.0  
1  396.90   9.14   21.6  
2  392.83   4.03   34.7  
3  394.63   2.94   33.4  
4  396.90   5.33   36.2

In [7]:
df.nunique()

CRIM       504
ZN          26
INDUS       76
CHAS         2
NOX         81
RM         446
AGE        356
DIS        412
RAD          9
TAX         66
PTRATIO     46
B          357
LSTAT      455
PRICE      229
dtype: int64

In [8]:
query = df.RM < 6.998

In [10]:
df[query].head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD  TAX  PTRATIO  \
0  0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296     15.3   
1  0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242     17.8   
3  0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222     18.7   
5  0.02985   0.0   2.18     0  0.458  6.430  58.7  6.0622    3  222     18.7   
6  0.08829  12.5   7.87     0  0.524  6.012  66.6  5.5605    5  311     15.2   

        B  LSTAT  PRICE  
0  396.90   4.98   24.0  
1  396.90   9.14   21.6  
3  394.63   2.94   33.4  
5  394.12   5.21   28.7  
6  395.60  12.43   22.9

In [11]:
df[~query].head()

CRIM    ZN  INDUS  CHAS     NOX     RM   AGE     DIS  RAD  TAX  \
2   0.02729   0.0   7.07     0  0.4690  7.185  61.1  4.9671    2  242   
4   0.06905   0.0   2.18     0  0.4580  7.147  54.2  6.0622    3  222   
40  0.03359  75.0   2.95     0  0.4280  7.024  15.8  5.4011    3  252   
55  0.01311  90.0   1.22     0  0.4030  7.249  21.9  8.6966    5  226   
64  0.01951  17.5   1.38     0  0.4161  7.104  59.5  9.2229    3  216   

    PTRATIO       B  LSTAT  PRICE  
2      17.8  392.83   4.03   34.7  
4      18.7  396.90   5.33   36.2  
40     18.3  395.62   1.98   34.9  
55     17.9  395.93   4.81   35.4  
64     18.6  393.24   8.05   33.0

In [17]:
df.size

7084

In [18]:
tree = DecisionTreeRegressor()

In [20]:
tree.get_params()

{'criterion': 'mse',
 'max_depth': None,
 'max_features': None,
 'max_leaf_nodes': None,
 'min_impurity_decrease': 0.0,
 'min_impurity_split': None,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'presort': False,
 'random_state': None,
 'splitter': 'best'}

In [21]:
from sklearn.model_selection import cross_val_score

Checking out different min leaf sample parameter

In [23]:
X = df.iloc[:,:-1]
y = df.PRICE

In [59]:
leaf_size = [1, 5, 10, 15, 25]
cross_val_scores = []

for size in leaf_size:
    tree.set_params(min_samples_leaf=size)
    scores = cross_val_score(estimator=tree, X=X, y=y,cv=10)
    cross_val_scores.append((round(np.mean(scores), 5), size))

In [60]:
pd.options.display.float_format = '{:.2f}'.format
cross_val_scores

[(-0.13661, 1), (0.11589, 5), (0.30537, 10), (0.21664, 15), (0.20378, 25)]

In [63]:
from sklearn.ensemble import RandomForestRegressor

In [80]:
rf = RandomForestRegressor()

In [68]:
rf.get_params()

{'bootstrap': True,
 'criterion': 'mse',
 'max_depth': None,
 'max_features': 'auto',
 'max_leaf_nodes': None,
 'min_impurity_decrease': 0.0,
 'min_impurity_split': None,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'n_estimators': 'warn',
 'n_jobs': None,
 'oob_score': False,
 'random_state': None,
 'verbose': 0,
 'warm_start': False}

In [70]:
??rf

In [81]:
rf.set_params(n_estimators=10)

RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=None,
                      max_features='auto', max_leaf_nodes=None,
                      min_impurity_decrease=0.0, min_impurity_split=None,
                      min_samples_leaf=1, min_samples_split=2,
                      min_weight_fraction_leaf=0.0, n_estimators=10,
                      n_jobs=None, oob_score=False, random_state=None,
                      verbose=0, warm_start=False)

In [102]:
feature_size = [0.05, 0.1, 0.2, .3, .4, .5, .6, .7, .8, .9, 1]
cross_val_scores = []
for size in feature_size:
    rf.set_params(max_features = size)
    rf.set_params(n_estimators=40)
    rf.set_params(random_state=2019)
    scores = cross_val_score(estimator = rf, X=X, y=y, cv=10)
    cross_val_scores.append((np.mean(scores), size))
cross_val_scores

[(0.31717904278279424, 0.05),
 (0.31717904278279424, 0.1),
 (0.44877971588542803, 0.2),
 (0.4911770690615226, 0.3),
 (0.5808183820136581, 0.4),
 (0.5797852214532969, 0.5),
 (0.5913014465133475, 0.6),
 (0.5617466437683387, 0.7),
 (0.5569684941152964, 0.8),
 (0.5235994501152816, 0.9),
 (0.31717904278279424, 1)]

In [104]:
num_trees = [10, 40, 50, 80, 100]
cross_val_scores = []
for size in num_trees:
    rf.set_params(max_features = .5)
    rf.set_params(n_estimators=size)
    rf.set_params(random_state=2019)
    scores = cross_val_score(estimator = rf, X=X, y=y, cv=10)
    cross_val_scores.append((np.mean(scores), size))
cross_val_scores

[(0.5046582961001771, 10),
 (0.5797852214532969, 40),
 (0.5683222567830677, 50),
 (0.5775055264903067, 80),
 (0.5781810702228942, 100)]

Regularization

In [105]:
from sklearn.linear_model import LinearRegression

lreg = LinearRegression()

In [106]:
lreg.fit(X, y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [110]:
pd.Series(lreg.coef_)

0     -0.11
1      0.05
2      0.02
3      2.69
4    -17.77
5      3.81
6      0.00
7     -1.48
8      0.31
9     -0.01
10    -0.95
11     0.01
12    -0.52
dtype: float64

In [111]:
lreg.coef_

array([-1.08011358e-01,  4.64204584e-02,  2.05586264e-02,  2.68673382e+00,
       -1.77666112e+01,  3.80986521e+00,  6.92224640e-04, -1.47556685e+00,
        3.06049479e-01, -1.23345939e-02, -9.52747232e-01,  9.31168327e-03,
       -5.24758378e-01])

In [112]:
from sklearn.linear_model import Ridge, Lasso

In [179]:
rreg= Ridge()
lasso = Lasso()

In [114]:
rreg.get_params()

{'alpha': 1.0,
 'copy_X': True,
 'fit_intercept': True,
 'max_iter': None,
 'normalize': False,
 'random_state': None,
 'solver': 'auto',
 'tol': 0.001}

In [116]:
lasso.get_params()

{'alpha': 1.0,
 'copy_X': True,
 'fit_intercept': True,
 'max_iter': 1000,
 'normalize': False,
 'positive': False,
 'precompute': False,
 'random_state': None,
 'selection': 'cyclic',
 'tol': 0.0001,
 'warm_start': False}

In [119]:
alphas = np.logspace(-4,4,9)

In [126]:
X = (X-X.mean())/X.std()

In [154]:
rreg_scores = []
for alpha in alphas:
    rreg.set_params(alpha=alpha)
    scores = cross_val_score(estimator=rreg, X=X, y=y, cv=10)
    rreg_scores.append((np.mean(scores), alpha))

In [155]:
rreg_scores

[(0.20252963117308723, 0.0001),
 (0.2025354010157486, 0.001),
 (0.20259308261316894, 0.01),
 (0.20316822226107858, 0.1),
 (0.2087582466065651, 1.0),
 (0.2526804803871787, 10.0),
 (0.35666897651456553, 100.0),
 (0.05942429977633958, 1000.0),
 (-0.815691966079091, 10000.0)]

In [135]:
max(rreg_scores)

(0.35666897651456553, 100.0)

In [158]:
rreg.fit(X, y)

Ridge(alpha=10000.0, copy_X=True, fit_intercept=True, max_iter=None,
      normalize=False, random_state=None, solver='auto', tol=0.001)

In [152]:
cross_val_score(estimator=rreg, X=X, y=y, cv=10)

array([-0.00996014,  0.08371599, -2.3401244 , -0.68043634, -0.25690751,
       -0.9058174 , -0.00814297, -0.05532743, -3.63273452, -0.35118494])

In [151]:
rreg

Ridge(alpha=10000.0, copy_X=True, fit_intercept=True, max_iter=None,
      normalize=False, random_state=None, solver='auto', tol=0.001)

In [159]:
rreg.coef_

array([-0.13817449,  0.12573267, -0.168168  ,  0.07565151, -0.14515968,
        0.28031619, -0.12618334,  0.06808496, -0.12562302, -0.16215118,
       -0.19566084,  0.12094646, -0.28502685])

In [182]:
lasso_scores = []
for alpha in alphas:
    lasso.set_params(alpha=alpha)
    scores = cross_val_score(estimator=lasso, X=X, y=y, cv=10)
    lasso_scores.append((np.mean(scores), alpha))

In [183]:
lasso_scores

[(0.20262012278999347, 0.0001),
 (0.20343535169466956, 0.001),
 (0.21144430759385185, 0.01),
 (0.2407890782467927, 0.1),
 (0.1807548507575551, 1.0),
 (-1.2860830508551744, 10.0),
 (-1.2860830508551744, 100.0),
 (-1.2860830508551744, 1000.0),
 (-1.2860830508551744, 10000.0)]

In [184]:
lasso.fit(X,y)

Lasso(alpha=10000.0, copy_X=True, fit_intercept=True, max_iter=1000,
      normalize=False, positive=False, precompute=False, random_state=None,
      selection='cyclic', tol=0.0001, warm_start=False)

In [185]:
lasso.coef_

array([-0.,  0., -0.,  0., -0.,  0., -0.,  0., -0., -0., -0.,  0., -0.])

In [187]:
lasso.set_params(alpha = 0.1)

Lasso(alpha=0.1, copy_X=True, fit_intercept=True, max_iter=1000,
      normalize=False, positive=False, precompute=False, random_state=None,
      selection='cyclic', tol=0.0001, warm_start=False)

In [188]:
lasso.fit(X,y)

Lasso(alpha=0.1, copy_X=True, fit_intercept=True, max_iter=1000,
      normalize=False, positive=False, precompute=False, random_state=None,
      selection='cyclic', tol=0.0001, warm_start=False)

In [190]:
pd.Series(lasso.coef_)

0    -0.63
1     0.71
2    -0.00
3     0.66
4    -1.58
5     2.83
6    -0.00
7    -2.42
8     1.20
9    -0.85
10   -1.92
11    0.76
12   -3.73
dtype: float64