In [1]:
import numpy as np
import pandas as pd

In [2]:
matrix = np.arange(20).reshape(5,4)

In [3]:
matrix

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [4]:
np.arange(20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [5]:
matrix.mean()

9.5

In [6]:
matrix ** 2

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121],
       [144, 169, 196, 225],
       [256, 289, 324, 361]])

In [7]:
matrix[:3,2:4]

array([[ 2,  3],
       [ 6,  7],
       [10, 11]])

In [8]:
matrix[:3,2:4].mean()

6.5

In [9]:
matrix

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [10]:
matrix.mean(axis = 0)

array([ 8.,  9., 10., 11.])

In [11]:
matrix.mean(axis = 1)

array([ 1.5,  5.5,  9.5, 13.5, 17.5])

In [12]:
matrix.any()

True

In [13]:
matrix.all()

False

In [14]:
df = pd.read_csv('/Users/devonbancroft/Desktop/DAT-10-14/class material/Unit1/data/titanic.csv')

In [15]:
df.set_index('PassengerId')

Survived  Pclass  \
PassengerId                     
1                   0       3   
2                   1       1   
3                   1       3   
4                   1       1   
5                   0       3   
6                   0       3   
7                   0       1   
8                   0       3   
9                   1       3   
10                  1       2   
11                  1       3   
12                  1       1   
13                  0       3   
14                  0       3   
15                  0       3   
16                  1       2   
17                  0       3   
18                  1       2   
19                  0       3   
20                  1       3   
21                  0       2   
22                  1       2   
23                  1       3   
24                  1       1   
25                  0       3   
26                  1       3   
27                  0       3   
28                  0       1   
29                  1       3   
30                  0       3   
...               ...     ...   
862                 0       2   
863                 1       1   
864                 0       3   
865                 0       2   
866                 1       2   
867                 1       2   
868                 0       1   
869                 0       3   
870                 1       3   
871                 0       3   
872                 1       1   
873                 0       1   
874                 0       3   
875                 1       2   
876                 1       3   
877                 0       3   
878                 0       3   
879                 0       3   
880                 1       1   
881                 1       2   
882                 0       3   
883                 0       3   
884                 0       2   
885                 0       3   
886                 0       3   
887                 0       2   
888                 1       1   
889                 0       3   
890                 1       1   
891                 0       3   

                                                          Name     Sex   Age  \
PassengerId                                                                    
1                                      Braund, Mr. Owen Harris    male  22.0   
2            Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0   
3                                       Heikkinen, Miss. Laina  female  26.0   
4                 Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0   
5                                     Allen, Mr. William Henry    male  35.0   
6                                             Moran, Mr. James    male   NaN   
7                                      McCarthy, Mr. Timothy J    male  54.0   
8                               Palsson, Master. Gosta Leonard    male   2.0   
9            Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  27.0   
10                         Nasser, Mrs. Nicholas (Adele Achem)  female  14.0   
11                             Sandstrom, Miss. Marguerite Rut  female   4.0   
12                                    Bonnell, Miss. Elizabeth  female  58.0   
13                              Saundercock, Mr. William Henry    male  20.0   
14                                 Andersson, Mr. Anders Johan    male  39.0   
15                        Vestrom, Miss. Hulda Amanda Adolfina  female  14.0   
16                            Hewlett, Mrs. (Mary D Kingcome)   female  55.0   
17                                        Rice, Master. Eugene    male   2.0   
18                                Williams, Mr. Charles Eugene    male   NaN   
19           Vander Planke, Mrs. Julius (Emelia Maria Vande...  female  31.0   
20                                     Masselmani, Mrs. Fatima  female   NaN   
21                                        Fynney, Mr. Joseph J    male  35.0   
22                                       Beesley, Mr. Lawrence    male  34.0   
23           

In [16]:
df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [17]:
df[df.Cabin.isna() == True]

PassengerId  Survived  Pclass  \
0              1         0       3   
2              3         1       3   
4              5         0       3   
5              6         0       3   
7              8         0       3   
8              9         1       3   
9             10         1       2   
12            13         0       3   
13            14         0       3   
14            15         0       3   
15            16         1       2   
16            17         0       3   
17            18         1       2   
18            19         0       3   
19            20         1       3   
20            21         0       2   
22            23         1       3   
24            25         0       3   
25            26         1       3   
26            27         0       3   
28            29         1       3   
29            30         0       3   
30            31         0       1   
32            33         1       3   
33            34         0       2   
34            35         0       1   
35            36         0       1   
36            37         1       3   
37            38         0       3   
38            39         0       3   
..           ...       ...     ...   
852          853         0       3   
854          855         0       2   
855          856         1       3   
856          857         1       1   
858          859         1       3   
859          860         0       3   
860          861         0       3   
861          862         0       2   
863          864         0       3   
864          865         0       2   
865          866         1       2   
866          867         1       2   
868          869         0       3   
869          870         1       3   
870          871         0       3   
873          874         0       3   
874          875         1       2   
875          876         1       3   
876          877         0       3   
877          878         0       3   
878          879         0       3   
880          881         1       2   
881          882         0       3   
882          883         0       3   
883          884         0       2   
884          885         0       3   
885          886         0       3   
886          887         0       2   
888          889         0       3   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
4                             Allen, Mr. William Henry    male  35.0      0   
5                                     Moran, Mr. James    male   NaN      0   
7                       Palsson, Master. Gosta Leonard    male   2.0      3   
8    Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  27.0      0   
9                  Nasser, Mrs. Nicholas (Adele Achem)  female  14.0      1   
12                      Saundercock, Mr. William Henry    male  20.0      0   
13                         Andersson, Mr. Anders Johan    male  39.0      1   
14                Vestrom, Miss. Hulda Amanda Adolfina  female  14.0      0   
15                    Hewlett, Mrs. (Mary D Kingcome)   female  55.0      0   
16                                Rice, Master. Eugene    male   2.0      4   
17                        Williams, Mr. Charles Eugene    male   NaN      0   
18   Vander Planke, Mrs. Julius (Emelia Maria Vande...  female  31.0      1   
19                             Masselmani, Mrs. Fatima  female   NaN      0   
20                                Fynney, Mr. Joseph J    male  35.0      0   
22                         McGowan, Miss. Anna "Annie"  female  15.0      0   
24                       Palsson, Miss. Torborg Danira  female   8.0      3   
25   Asplund, Mrs. Carl Oscar (Selma Augusta Emilia...  female  38.0      1   
26                             Emir, Mr. Farred Chehab    male   NaN

In [18]:
type(df)

pandas.core.frame.DataFrame

In [19]:
df.shape

(891, 12)

In [20]:
df['Survived'].index

RangeIndex(start=0, stop=891, step=1)

In [21]:
df[['Age','Survived']]

Age  Survived
0    22.0         0
1    38.0         1
2    26.0         1
3    35.0         1
4    35.0         0
5     NaN         0
6    54.0         0
7     2.0         0
8    27.0         1
9    14.0         1
10    4.0         1
11   58.0         1
12   20.0         0
13   39.0         0
14   14.0         0
15   55.0         1
16    2.0         0
17    NaN         1
18   31.0         0
19    NaN         1
20   35.0         0
21   34.0         1
22   15.0         1
23   28.0         1
24    8.0         0
25   38.0         1
26    NaN         0
27   19.0         0
28    NaN         1
29    NaN         0
..    ...       ...
861  21.0         0
862  48.0         1
863   NaN         0
864  24.0         0
865  42.0         1
866  27.0         1
867  31.0         0
868   NaN         0
869   4.0         1
870  26.0         0
871  47.0         1
872  33.0         0
873  47.0         0
874  28.0         1
875  15.0         1
876  20.0         0
877  19.0         0
878   NaN         0
879  56.0         1
880  25.0         1
881  33.0         0
882  22.0         0
883  28.0         0
884  25.0         0
885  39.0         0
886  27.0         0
887  19.0         1
888   NaN         0
889  26.0         1
890  32.0         0

[891 rows x 2 columns]

In [22]:
num_cols = df.select_dtypes(include=np.number).columns.tolist()
num_cols

['PassengerId', 'Survived', 'Pclass', 'Age', 'SibSp', 'Parch', 'Fare']

In [23]:
df[df.select_dtypes(include=np.number).columns.tolist()]

PassengerId  Survived  Pclass   Age  SibSp  Parch      Fare
0              1         0       3  22.0      1      0    7.2500
1              2         1       1  38.0      1      0   71.2833
2              3         1       3  26.0      0      0    7.9250
3              4         1       1  35.0      1      0   53.1000
4              5         0       3  35.0      0      0    8.0500
5              6         0       3   NaN      0      0    8.4583
6              7         0       1  54.0      0      0   51.8625
7              8         0       3   2.0      3      1   21.0750
8              9         1       3  27.0      0      2   11.1333
9             10         1       2  14.0      1      0   30.0708
10            11         1       3   4.0      1      1   16.7000
11            12         1       1  58.0      0      0   26.5500
12            13         0       3  20.0      0      0    8.0500
13            14         0       3  39.0      1      5   31.2750
14            15         0       3  14.0      0      0    7.8542
15            16         1       2  55.0      0      0   16.0000
16            17         0       3   2.0      4      1   29.1250
17            18         1       2   NaN      0      0   13.0000
18            19         0       3  31.0      1      0   18.0000
19            20         1       3   NaN      0      0    7.2250
20            21         0       2  35.0      0      0   26.0000
21            22         1       2  34.0      0      0   13.0000
22            23         1       3  15.0      0      0    8.0292
23            24         1       1  28.0      0      0   35.5000
24            25         0       3   8.0      3      1   21.0750
25            26         1       3  38.0      1      5   31.3875
26            27         0       3   NaN      0      0    7.2250
27            28         0       1  19.0      3      2  263.0000
28            29         1       3   NaN      0      0    7.8792
29            30         0       3   NaN      0      0    7.8958
..           ...       ...     ...   ...    ...    ...       ...
861          862         0       2  21.0      1      0   11.5000
862          863         1       1  48.0      0      0   25.9292
863          864         0       3   NaN      8      2   69.5500
864          865         0       2  24.0      0      0   13.0000
865          866         1       2  42.0      0      0   13.0000
866          867         1       2  27.0      1      0   13.8583
867          868         0       1  31.0      0      0   50.4958
868          869         0       3   NaN      0      0    9.5000
869          870         1       3   4.0      1      1   11.1333
870          871         0       3  26.0      0      0    7.8958
871          872         1       1  47.0      1      1   52.5542
872          873         0       1  33.0      0      0    5.0000
873          874         0       3  47.0      0      0    9.0000
874          875         1       2  28.0      1      0   24.0000
875          876         1       3  15.0      0      0    7.2250
876          877         0       3  20.0      0      0    9.8458
877          878         0       3  19.0      0      0    7.8958
878          879         0       3   NaN      0      0    7.8958
879          880         1       1  56.0      0      1   83.1583
880          881         1       2  25.0      0      1   26.0000
881          882         0       3  33.0      0      0    7.8958
882          883         0       3  22.0      0      0   10.5167
883          884         0       2  28.0      0      0   10.5000
884          885         0       3  25.0      0      0    7.0500
885          886         0       3  39.0      0      5   29.1250
886          887         0       2  27.0      0      0   13.0000
887          888         1       1  19.0      0      0   30.0000
888          889         0       3   NaN      1      2   23.4500
889          890         1       1  26.0      0      0   30.0000
890          891         0       3  32.0

In [24]:
df[num_cols][:100]

PassengerId  Survived  Pclass    Age  SibSp  Parch      Fare
0             1         0       3  22.00      1      0    7.2500
1             2         1       1  38.00      1      0   71.2833
2             3         1       3  26.00      0      0    7.9250
3             4         1       1  35.00      1      0   53.1000
4             5         0       3  35.00      0      0    8.0500
5             6         0       3    NaN      0      0    8.4583
6             7         0       1  54.00      0      0   51.8625
7             8         0       3   2.00      3      1   21.0750
8             9         1       3  27.00      0      2   11.1333
9            10         1       2  14.00      1      0   30.0708
10           11         1       3   4.00      1      1   16.7000
11           12         1       1  58.00      0      0   26.5500
12           13         0       3  20.00      0      0    8.0500
13           14         0       3  39.00      1      5   31.2750
14           15         0       3  14.00      0      0    7.8542
15           16         1       2  55.00      0      0   16.0000
16           17         0       3   2.00      4      1   29.1250
17           18         1       2    NaN      0      0   13.0000
18           19         0       3  31.00      1      0   18.0000
19           20         1       3    NaN      0      0    7.2250
20           21         0       2  35.00      0      0   26.0000
21           22         1       2  34.00      0      0   13.0000
22           23         1       3  15.00      0      0    8.0292
23           24         1       1  28.00      0      0   35.5000
24           25         0       3   8.00      3      1   21.0750
25           26         1       3  38.00      1      5   31.3875
26           27         0       3    NaN      0      0    7.2250
27           28         0       1  19.00      3      2  263.0000
28           29         1       3    NaN      0      0    7.8792
29           30         0       3    NaN      0      0    7.8958
..          ...       ...     ...    ...    ...    ...       ...
70           71         0       2  32.00      0      0   10.5000
71           72         0       3  16.00      5      2   46.9000
72           73         0       2  21.00      0      0   73.5000
73           74         0       3  26.00      1      0   14.4542
74           75         1       3  32.00      0      0   56.4958
75           76         0       3  25.00      0      0    7.6500
76           77         0       3    NaN      0      0    7.8958
77           78         0       3    NaN      0      0    8.0500
78           79         1       2   0.83      0      2   29.0000
79           80         1       3  30.00      0      0   12.4750
80           81         0       3  22.00      0      0    9.0000
81           82         1       3  29.00      0      0    9.5000
82           83         1       3    NaN      0      0    7.7875
83           84         0       1  28.00      0      0   47.1000
84           85         1       2  17.00      0      0   10.5000
85           86         1       3  33.00      3      0   15.8500
86           87         0       3  16.00      1      3   34.3750
87           88         0       3    NaN      0      0    8.0500
88           89         1       1  23.00      3      2  263.0000
89           90         0       3  24.00      0      0    8.0500
90           91         0       3  29.00      0      0    8.0500
91           92         0       3  20.00      0      0    7.8542
92           93         0       1  46.00      1      0   61.1750
93           94         0       3  26.00      1      2   20.5750
94           95         0       3  59.00      0      0    7.2500
95           96         0       3    NaN      0      0    8.0500
96           97         0       1  71.00      0      0   34.6542
97           98         1       1  23.00      0      1   63.3583
98           99         1       2  34.00      0      1   23.0000
99          100         0       2  34.0

In [25]:
df[num_cols].iloc[:25,2:6]

Pclass   Age  SibSp  Parch
0        3  22.0      1      0
1        1  38.0      1      0
2        3  26.0      0      0
3        1  35.0      1      0
4        3  35.0      0      0
5        3   NaN      0      0
6        1  54.0      0      0
7        3   2.0      3      1
8        3  27.0      0      2
9        2  14.0      1      0
10       3   4.0      1      1
11       1  58.0      0      0
12       3  20.0      0      0
13       3  39.0      1      5
14       3  14.0      0      0
15       2  55.0      0      0
16       3   2.0      4      1
17       2   NaN      0      0
18       3  31.0      1      0
19       3   NaN      0      0
20       2  35.0      0      0
21       2  34.0      0      0
22       3  15.0      0      0
23       1  28.0      0      0
24       3   8.0      3      1

In [26]:
df.iloc[:25,[0,3,4,7]]

PassengerId                                               Name     Sex  \
0             1                            Braund, Mr. Owen Harris    male   
1             2  Cumings, Mrs. John Bradley (Florence Briggs Th...  female   
2             3                             Heikkinen, Miss. Laina  female   
3             4       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female   
4             5                           Allen, Mr. William Henry    male   
5             6                                   Moran, Mr. James    male   
6             7                            McCarthy, Mr. Timothy J    male   
7             8                     Palsson, Master. Gosta Leonard    male   
8             9  Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female   
9            10                Nasser, Mrs. Nicholas (Adele Achem)  female   
10           11                    Sandstrom, Miss. Marguerite Rut  female   
11           12                           Bonnell, Miss. Elizabeth  female   
12           13                     Saundercock, Mr. William Henry    male   
13           14                        Andersson, Mr. Anders Johan    male   
14           15               Vestrom, Miss. Hulda Amanda Adolfina  female   
15           16                   Hewlett, Mrs. (Mary D Kingcome)   female   
16           17                               Rice, Master. Eugene    male   
17           18                       Williams, Mr. Charles Eugene    male   
18           19  Vander Planke, Mrs. Julius (Emelia Maria Vande...  female   
19           20                            Masselmani, Mrs. Fatima  female   
20           21                               Fynney, Mr. Joseph J    male   
21           22                              Beesley, Mr. Lawrence    male   
22           23                        McGowan, Miss. Anna "Annie"  female   
23           24                       Sloper, Mr. William Thompson    male   
24           25                      Palsson, Miss. Torborg Danira  female   

    Parch  
0       0  
1       0  
2       0  
3       0  
4       0  
5       0  
6       0  
7       1  
8       2  
9       0  
10      1  
11      0  
12      0  
13      5  
14      0  
15      0  
16      1  
17      0  
18      0  
19      0  
20      0  
21      0  
22      0  
23      0  
24      1

In [27]:
df.mean(axis = 0)

PassengerId    446.000000
Survived         0.383838
Pclass           2.308642
Age             29.699118
SibSp            0.523008
Parch            0.381594
Fare            32.204208
dtype: float64

In [28]:
df.mean()

PassengerId    446.000000
Survived         0.383838
Pclass           2.308642
Age             29.699118
SibSp            0.523008
Parch            0.381594
Fare            32.204208
dtype: float64

In [29]:
df.iloc[:25,[0,3,4,7]].mean()

PassengerId    13.00
Parch           0.44
dtype: float64

In [30]:
df[:10]

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   
5            6         0       3   
6            7         0       1   
7            8         0       3   
8            9         1       3   
9           10         1       2   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   
5                                   Moran, Mr. James    male   NaN      0   
6                            McCarthy, Mr. Timothy J    male  54.0      0   
7                     Palsson, Master. Gosta Leonard    male   2.0      3   
8  Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  27.0      0   
9                Nasser, Mrs. Nicholas (Adele Achem)  female  14.0      1   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S  
5      0            330877   8.4583   NaN        Q  
6      0             17463  51.8625   E46        S  
7      1            349909  21.0750   NaN        S  
8      2            347742  11.1333   NaN        S  
9      0            237736  30.0708   NaN        C

In [31]:
df.Age.mean()

29.69911764705882

In [32]:
df[['Fare','SibSp']].median()

Fare     14.4542
SibSp     0.0000
dtype: float64

In [33]:
df[['Fare','SibSp']][:100].median()

Fare     15.675
SibSp     0.000
dtype: float64

In [34]:
df.iloc[:,-4:].mode()

Ticket  Fare        Cabin Embarked
0      1601  8.05      B96 B98        S
1    347082   NaN  C23 C25 C27      NaN
2  CA. 2343   NaN           G6      NaN

In [35]:
df.mode()

PassengerId  Survived  Pclass  \
0              1       0.0     3.0   
1              2       NaN     NaN   
2              3       NaN     NaN   
3              4       NaN     NaN   
4              5       NaN     NaN   
5              6       NaN     NaN   
6              7       NaN     NaN   
7              8       NaN     NaN   
8              9       NaN     NaN   
9             10       NaN     NaN   
10            11       NaN     NaN   
11            12       NaN     NaN   
12            13       NaN     NaN   
13            14       NaN     NaN   
14            15       NaN     NaN   
15            16       NaN     NaN   
16            17       NaN     NaN   
17            18       NaN     NaN   
18            19       NaN     NaN   
19            20       NaN     NaN   
20            21       NaN     NaN   
21            22       NaN     NaN   
22            23       NaN     NaN   
23            24       NaN     NaN   
24            25       NaN     NaN   
25            26       NaN     NaN   
26            27       NaN     NaN   
27            28       NaN     NaN   
28            29       NaN     NaN   
29            30       NaN     NaN   
..           ...       ...     ...   
861          862       NaN     NaN   
862          863       NaN     NaN   
863          864       NaN     NaN   
864          865       NaN     NaN   
865          866       NaN     NaN   
866          867       NaN     NaN   
867          868       NaN     NaN   
868          869       NaN     NaN   
869          870       NaN     NaN   
870          871       NaN     NaN   
871          872       NaN     NaN   
872          873       NaN     NaN   
873          874       NaN     NaN   
874          875       NaN     NaN   
875          876       NaN     NaN   
876          877       NaN     NaN   
877          878       NaN     NaN   
878          879       NaN     NaN   
879          880       NaN     NaN   
880          881       NaN     NaN   
881          882       NaN     NaN   
882          883       NaN     NaN   
883          884       NaN     NaN   
884          885       NaN     NaN   
885          886       NaN     NaN   
886          887       NaN     NaN   
887          888       NaN     NaN   
888          889       NaN     NaN   
889          890       NaN     NaN   
890          891       NaN     NaN   

                                                Name   Sex   Age  SibSp  \
0                                Abbing, Mr. Anthony  male  24.0    0.0   
1                        Abbott, Mr. Rossmore Edward   NaN   NaN    NaN   
2                   Abbott, Mrs. Stanton (Rosa Hunt)   NaN   NaN    NaN   
3                                Abelson, Mr. Samuel   NaN   NaN    NaN   
4              Abelson, Mrs. Samuel (Hannah Wizosky)   NaN   NaN    NaN   
5                     Adahl, Mr. Mauritz Nils Martin   NaN   NaN    NaN   
6                                    Adams, Mr. John   NaN   NaN    NaN   
7     Ahlin, Mrs. Johan (Johanna Persdotter Larsson)   NaN   NaN    NaN   
8                         Aks, Mrs. Sam (Leah Rosen)   NaN   NaN    NaN   
9                        Albimona, Mr. Nassef Cassem   NaN   NaN    NaN   
10                            Alexander, Mr. William   NaN   NaN    NaN   
11                       Alhomaki, Mr. Ilmari Rudolf   NaN   NaN    NaN   
12                                    Ali, Mr. Ahmed   NaN   NaN    NaN   
13                                  Ali, Mr. William   NaN   NaN    NaN   
14                     Allen, Miss. Elisabeth Walton   NaN   NaN    NaN   
15                          Allen, Mr. William Henry   NaN   NaN    NaN   
16                    Allison, Master. Hudson Trevor   NaN   NaN    NaN   
17                      Allison, Miss. Helen Loraine   NaN   NaN    NaN   
18   Allison, Mrs. Hudson J C (Bessie Waldo Daniels)   NaN   NaN    NaN   
19                            Allum, Mr. Owen George   NaN   NaN    NaN   
20   Andersen-Jensen, Miss. Carla Christine Nielsine   NaN   NaN    NaN  

In [36]:
df.iloc[:250,:3].mean()

PassengerId    125.500
Survived         0.344
Pclass           2.416
dtype: float64

In [37]:
df.head(2)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   

   Parch     Ticket     Fare Cabin Embarked  
0      0  A/5 21171   7.2500   NaN        S  
1      0   PC 17599  71.2833   C85        C

In [38]:
df[df.Sex == 'female'].iloc[:,1].count()

314

In [52]:
df[df.Sex == 'male'].iloc[:,1].shape[0]

577

In [40]:
df[df.Sex == 'female'].Survived.mean()

0.7420382165605095

In [41]:
df[df.Sex == 'male'].Survived.mean()

0.18890814558058924

In [42]:
df[(df.Pclass == 1) | (df.Pclass == 2)].Survived.mean()

0.5575

In [43]:
df[(df.Sex == 'female') & (df.SibSp > 0)].Survived.mean()

0.6857142857142857

In [44]:
df[(df.Sex == 'female') & (df.SibSp == 0)].Survived.mean()

0.7873563218390804

In [45]:
df['Total_Family_Size'] = df.SibSp + df.Parch

In [46]:
df.head(1)

PassengerId  Survived  Pclass                     Name   Sex   Age  SibSp  \
0            1         0       3  Braund, Mr. Owen Harris  male  22.0      1   

   Parch     Ticket  Fare Cabin Embarked  Total_Family_Size  
0      0  A/5 21171  7.25   NaN        S                  1

In [47]:
df['Is_Alone'] = df.Total_Family_Size == 0

In [48]:
df.

SyntaxError: invalid syntax (<ipython-input-48-38e9e33c87a8>, line 1)